### PR TITLE
Fix 3001/in-flight.

### PR DESCRIPTION
**Pull request by prabhakhar**

### CODE REVIEW

**Comment by prabhakhar** [comment]
Thought the problem was with only the rendering part.

http://localhost:3001/  itself not showing the data rightly. Looking into that.

**Comment by s3u** [comment]
Could you explain why showing URLs of in-flight requests is not possible?

**Comment by prabhakhar** [comment]
Currently, the page has a simple table with two columns. PID and NumOfRequests that process id handling. I will redesign the page and update the issue with the design.

**Comment by prabhakhar** [comment]
Will give a better page for in flight.

**Pull request closed without merging**
