### PR TITLE
Tweaks for Avro support

### PR DESCRIPTION
**Pull request by sjcarriere**
Added a dependency on the new Avro module.
Also made a change to uri-template to not URL encode path components (may not be a good fix).

### CODE REVIEW

**Comment by s3u** [comment]
Will merge into 0.4.x once 0.4 is out on Monday.

**Comment by s3u** [comment]
@sjcarriere - Can you share some test data to test this? We need to add a unit test.

**Comment by sjcarriere** [comment]
The Avro implementation uses idioms specific to X.commerce, specifically:
- schema handling using the X-XC-SCHEMA-VERSION and X-XC-SCHEMA-URI headers
- topic handling based on the convention used by the sync bridge (X-XB-TOPIC)

**Comment by s3u** [comment]
@sjcarriere I see the generated .js, but peg for uri-template is missing.

**Comment by s3u** [comment]
@sjcarriere minor nitpick: tabs :)

**Comment by s3u** [comment]
@sjcarriere I think it is better to use some convention for schema locations to avoid dependencies on x-xc-schema-uri and x-xb-topic to keep the core clean. 

Let's just say that the location is always the tables dir, and the topic name name is the name of the table. Would it work?

Then I can load up the schema at table loading time, and hand it off to the xformer at req time.

**Comment by sjcarriere** [comment]
Not sure how that would work - those two headers are the mechanism for
schema resolution, and need to be determined at runtime.  I definitely
recognize that this stuff isn't appropriate in the core (I hesitated
submitting it at all, in fact), so I think we'll need to externalize this
processing somehow - into user space.

On 2/13/12 9:28 PM, "Subbu Allamaraju"
<reply+i-3185247-0de560b28f0491df60669f593f869930ad3d9a1f-684834@reply.gith
ub.com> wrote:

**Comment by sjcarriere** [comment]
uri-template.peg committed

On 2/13/12 9:15 PM, "Subbu Allamaraju"
<reply+i-3185247-0de560b28f0491df60669f593f869930ad3d9a1f-684834@reply.gith
ub.com> wrote:

**Comment by s3u** [comment]
modules/uri-template/test/uri-template-test.js:encode is failing as the values of params are not getting encoded due the change in the peg. Is the encoding breaking the fabric's usage?

**Comment by sjcarriere** [comment]
The issue was encoding of params in the URL. My bad for not testing.

~j (mobile)

**Comment by s3u** [comment]
If you had to do this, there must be a problem elsewhere. Do you have an example that I can try?

**Comment by sjcarriere** [comment]
Just try to put a param with a slash in it into uri

~j (mobile)

**Comment by s3u** [comment]
Like `http://localhost:9091/invoke/{topic}` where `topic` is `foo/bar`?

**Comment by sjcarriere** [comment]
Yep

~j (mobile)

**Comment by s3u** [comment]
I think I can fix that. I will extend your changes with my fix and merge together.

**Comment by sjcarriere** [comment]
Thanks.

~j (mobile)

**Comment by s3u** [comment]
Prefix the token with '`' to prevent escaping. Here is an example.

```
http://www.foo.com/{`p1}/baz
```

The value of the token `p1` won't be encoded.

**Comment by sjcarriere** [comment]
Is this in the main repo?

On 2/15/12 12:33 PM, "Subbu Allamaraju"
<reply+i-3185247-0de560b28f0491df60669f593f869930ad3d9a1f-684834@reply.gith
ub.com> wrote:

**Comment by s3u** [comment]
Yes. The test is at

https://github.com/ql-io/ql.io/blob/master/modules/uri-template/test/uri-template-test.js#L281

I've not pushed to npm yet as I'm waiting for one more change.

**Comment by sjcarriere** [comment]
If I pull and make, I should get it, no?

On 2/15/12 3:01 PM, "Subbu Allamaraju"
<reply+i-3185247-0de560b28f0491df60669f593f869930ad3d9a1f-684834@reply.gith
ub.com> wrote:

**Comment by s3u** [comment]
Since you're on a fork, no. You will need to setup a remote and fetch the remote as per http://help.github.com/fork-a-repo/.

```
# Do this once
git remote add upstream git@github.com:ql-io/ql.io.git

# Do this everytime you want to sync your fork with upstream
git fetch upstream
git merge upstream/master
```

**Comment by sjcarriere** [comment]
Ok, thanks.  I did a fresh pull off the main repo, though that should
have gotten the change, I presume?

On 2/15/12 3:08 PM, "Subbu Allamaraju"
<reply+i-3185247-0de560b28f0491df60669f593f869930ad3d9a1f-684834@reply.gith
ub.com> wrote:

**Comment by sjcarriere** [comment]
Not working for me.

My table definition is:

create table producttaxonomy on select post to
'http://localhost:9091/invoke/{`topic}'
using headers
      'X-XB-BRIDGEKEY'='{config.SyncBridge.bridgekey}',
      'Authorization'='{config.Fabric.authorization}',
      'X-XB-RESPONSE-TOPICS'='/productTaxonomy/getSucceeded',
      'X-XC-SCHEMA-VERSION'='1.0.0',
      'X-XB-TIMEOUT'='10000'
using defaults topic='/productTaxonomy/get',
query='{"filter":{"detailLevel":1}}'
using patch 'x.js'
using bodyTemplate 'empty.mu' type 'avro/binary'

In uri-template.js,
    var encode = !ele.dontencode;
is true.

ele is
  {"variable":"topic"}

On 2/15/12 3:01 PM, "Subbu Allamaraju"
<reply+i-3185247-0de560b28f0491df60669f593f869930ad3d9a1f-684834@reply.gith
ub.com> wrote:

**Comment by s3u** [comment]
I'll repro tonight.

**Comment by sjcarriere** [comment]
Danke.

On 2/15/12 6:37 PM, "Subbu Allamaraju"
<reply+i-3185247-0de560b28f0491df60669f593f869930ad3d9a1f-684834@reply.gith
ub.com> wrote:

**Comment by s3u** [comment]
Here is a test I just did

```
cd /tmp
npm link ql.io-uri-template

# enter node  
ut = require('ql.io-uri-template');
str = 'http://localhost:9091/invoke/{`topic}';
template = ut.parse(str);
template.format({topic: '/productTaxonomy/get'})
```

The last statement prints

```
'http://localhost:9091/invoke//productTaxonomy/get'
```

**Comment by s3u** [comment]
Also tried with 

```
npm install ql.io-uri-template
```

Are you seeing a different behavior?

**Comment by sjcarriere** [comment]
This works as expected.  Do you get the correct behavior in the console?

On 2/15/12 8:59 PM, "Subbu Allamaraju"
<reply+i-3185247-0de560b28f0491df60669f593f869930ad3d9a1f-684834@reply.gith
ub.com> wrote:

**Comment by sjcarriere** [comment]
It works fine when I create a table in the console:

create table abc on select get from 'http://localhost:3011/{`test}' using
defaults test='a/b/c'

But _not_ when I load a table definition from a file at startup.

~j

On 2/15/12 9:01 PM, "Subbu Allamaraju"
<reply+i-3185247-0de560b28f0491df60669f593f869930ad3d9a1f-684834@reply.gith
ub.com> wrote:

**Comment by s3u** [comment]
Here is what I tried.
1. Drop the statement  
   
   create table abc on select get from 'http://localhost:3011/{`test}' using defaults test='a/b/c'

in a tables/abc.ql
2. Start the server
3. Run

```
select * from abc;
```

The HAR viewer shows the URI as `http://localhost:3011/a/b/c`

**Comment by s3u** [comment]
Table parsing happens in brew.js whether the `create table` is loaded from a file on the disk or a statement entered in the console. It is still likely that some bits are not consistently represented, but I'm not able to confirm the behavior your are seeing.

**Comment by sjcarriere** [comment]
Damn ... I'll keep digging.

~j (mobile)

**Comment by sjcarriere** [comment]
Solved it.  Once again, I got burned by a table.ql~ file (Emacs backup)
taking precedence over table.ql.

On 2/16/12 7:52 AM, "Subbu Allamaraju"
<reply+i-3185247-0de560b28f0491df60669f593f869930ad3d9a1f-684834@reply.gith
ub.com> wrote:

**Comment by s3u** [comment]
Fix coming up.

**Comment by s3u** [comment]
Fix in the queue - https://github.com/ql-io/ql.io/pull/285

**Comment by s3u** [comment]
Just FYI, I made a change to 'parse response' patch signature. In stead of getting one buffer with all bytes, it will now receive an array of buffers. This is done to avoid in-memory buffer copying. The default impl now looks like

exports['parse response'] = function(args) {
    var str = '';
    _.each(args.body, function(buf) {
        str += buf.toString('UTF-8');
    })
    return {
        type: 'application/json',
        content: str
    };
}

**Pull request merged**
