### PR TITLE
Handling 404s and sanitizing the returned url

### PR DESCRIPTION
**Pull request by prabhakhar**

### CODE REVIEW

**Comment by prabhakhar** [comment]
I like typed errors. 
If the req accepts json, then a json error message is returned. Otherwise, a plain text message. I do not see any security issue with that. Let me know if I am wrong or missed a better way to handle this.

**Comment by s3u** [comment]
@prabhakhar couple of follow ups

(a) changes.md and package.json are missing.
(b) port to 0.3.x as well.

**Comment by prabhakhar** [comment]
Expected some discussion before merge. Good that I got it right.
Will make the missing changes and give a pull request.

**Comment by s3u** [comment]
@prabhakhar not sure how git handles, but to keep sanity between 0.3 and master, we will also need a merge from 0.3.

**Comment by prabhakhar** [comment]
@s3u I will backport to 0.3 branch separately.

**Pull request merged**
