### PR TITLE
Fix for Issue #238 (Handle soap+xml in content subtype)

### PR DESCRIPTION
**Pull request by shimonchayim**

### CODE REVIEW

**Comment by s3u** [comment]
Just a minor nitpick - we don't really need that XML file to test the fix. A more appropriate test would to be to test support for different +xml media types as per http://www.ietf.org/rfc/rfc3023.txt.

**Comment by shimonchayim** [comment]
Ok, removed the big xml file.
Added test for soap+xml, atom+xml and foo+xml to cover expected and unexpected cases. Also fine tuned the condition to check for trailing "+xml" and not just "xml"
Modifying the pull request.

**Comment by shimonchayim** [comment]
Will also propogate the changes to 0.3 branch later tonight. Once the changes are accept.

**Comment by s3u** [comment]
One more thing - please also update CHANGES.md and modules/engine/package.json in both the branches.

**Comment by shimonchayim** [comment]
Will do.

**Pull request merged**
