### PR TITLE
Empty table def is warned, and will not hurt engine init.

### PR DESCRIPTION
**Pull request by prabhakhar**

### CODE REVIEW

**Comment by s3u** [comment]
Does it work? You can't depend on if(foo) when foo is an empty string but not when there is some white space or line breaks!

**Comment by s3u** [comment]
There are two things needed here
- fix the assert to do assert(script === 'undefined')
- let the compiler fail and report the failure as usual.

**Comment by prabhakhar** [comment]
1. I tested with an empty file. Didn't test with file having some white spaces.  
2. Empty table def files is fatal?

**Comment by s3u** [comment]
That assert is wrong and users should not see assert failures. We need to fix the assert.

**Pull request closed without merging**
