### PR TITLE
/ecv checks return network IP and hostname instead of loopback address

### PR DESCRIPTION
**Pull request by prabhakhar**

### CODE REVIEW

**Comment by prabhakhar** [comment]
I have tested in ql box.

**Comment by s3u** [comment]
That caching is unnecessary as the req.connection has the data from the network stack.

**Comment by prabhakhar** [comment]
I thought each time req object is a new one, Though the network stack has cached the value, I believe JS runtime can identify this caching and inline the value. 

If you think it is not necessary, I can remove.

**Comment by s3u** [comment]
I don't mean "cached value". It is coming afresh from TCP every time in the TCP header.

**Pull request merged**
