### PR TITLE
ifelse validation test

### PR DESCRIPTION
**Pull request by shimonchayim**

### CODE REVIEW

**Comment by s3u** [comment]
@shimonchayim - package.json for the engine and its dependents is missing.

**Comment by shimonchayim** [comment]
Sorry missed that .. will make the change

**Comment by s3u** [comment]
Also need to update package.json of modules that depend on the engine :)

Otherwise the change won't get picked up by those.

**Comment by s3u** [comment]
Merged as I'm waiting to push my changes.

**Pull request merged**
