### PR TITLE
update method

### PR DESCRIPTION
**Pull request by hochang**

### CODE REVIEW

**Comment by prabhakhar** [comment]
1. Have a test case with inner elements. something like,
   {  "id": "1", {"id": "1" } } or  { "id" :  { "id" : "2"}}  and try update.
2. Please modify the other test case to have a similar structure.
3. Have a test case which updates more than one node in the JSON.

**Comment by prabhakhar** [comment]
Do we need to support opaque params in 'update'.

**Comment by prabhakhar** [comment]
As we discussed, think about the behavior when the elements in LHS of the SET clause is not present in the JSON object being  updated. (Similarly, in real requests to APIs)

**Comment by hochang** [comment]
If an non-existing  field get updated, shall we insert this field or ignore?
e.g.
json = {
a : 1,
b : 2
}
updating field c = 3 should insert field c.

**Comment by hochang** [comment]
Do not delete this pull request. I leave it as a reference

**Pull request closed without merging**
