### PR TITLE
Support for HTML view for /routes & /tables

### PR DESCRIPTION
**Pull request by shimonchayim**

### CODE REVIEW

**Comment by s3u** [comment]
Since this pull req is large, I will test this on my box, and merge manually.

**Comment by shimonchayim** [comment]
Thanks!

**Comment by s3u** [comment]
I cloned your repo, and while make test, seeing errors like the following in an infinite loop.

```
^[[1mtest-table-metadata^[[22m
Error: Can't render headers after they are sent to the client.
    at ServerResponse.<anonymous> (http.js:562:11)
    at ServerResponse._renderHeaders (/Users/subrah/tmp/ql.io/modules/console/node_modules/connect/lib/patch.js:76:25)
    at ServerResponse.writeHead (http.js:824:20)
    at Object.handle (/Users/subrah/tmp/ql.io/modules/console/app.js:545:17)
    at next (/Users/subrah/tmp/ql.io/modules/console/node_modules/connect/lib/http.js:198:17)
    at next (/Users/subrah/tmp/ql.io/modules/console/node_modules/connect/lib/http.js:200:11)
    at pass (/Users/subrah/tmp/ql.io/modules/console/node_modules/express/lib/router/index.js:219:24)
    at nextRoute (/Users/subrah/tmp/ql.io/modules/console/node_modules/express/lib/router/index.js:209:7)
    at callbacks (/Users/subrah/tmp/ql.io/modules/console/node_modules/express/lib/router/index.js:274:11)
    at callbacks (/Users/subrah/tmp/ql.io/modules/console/node_modules/express/lib/router/index.js:277:9)
```

**Comment by s3u** [comment]
@prabhakhar could it be due to the xss fix?

**Comment by prabhakhar** [comment]
In my clone, tests are passing. Let me clone fresh and test.

**Comment by prabhakhar** [comment]
Fresh clone is good. Need to get Cylus code and see whether this is due to XSS fix.

**Comment by shimonchayim** [comment]
I was seeing this issue also on and off. Checked in when I stopped seeing this. Looks like it needs to be debugged through nodeunit. Hopefully this might help: http://www.jetbrains.com/idea/webhelp/run-debug-configuration-nodeunit.html

**Pull request merged**
